name: CI Pipeline
on:
  push:
    branches: [ main, reg-branch, hyper-branch ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run data loading test
      run: |
        python -c "
        from utils import load_data
        df = load_data()
        assert df is not None, 'Data loading failed'
        assert df.shape[0] > 0, 'Empty dataset'
        print('Data loading test passed')
        "
    
    - name: Run basic regression
      run: |
        python regression.py --mode basic
    
    - name: Run hyperparameter tuning (if on hyper-branch)
      if: contains(github.ref, 'hyper-branch')
      run: |
        python regression.py --mode tuned
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: regression-results
        path: |
          *.csv
          *.png
